### PR TITLE
Implement the Indirect jmp bug for NMOS

### LINKED ISSUE #86: Panic when executing `jmp ($ffff)`
While executing `jmp ($ffff)`, I get the following panic:

```
thread 'main' panicked at 'range end index 65537 out of range for slice of length 65536', /home/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mos6502-0.4.0/src/memory.rs:80:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The instruction reads two bytes from memory, and uses that two-byte value as a pointer to the jump's target. The implementation is trying to read a slice from the memory to get this pointer, but this fails when the real chip would read from address `$ffff`, wrapping over from the end of the address space to the beginning.

I appreciate that's the kind of thing we're vanishingly unlikely to run into in the wild, though!

### PR DESCRIPTION
**Pull request by omarandlorraine**
I've implemented the "hardware bug" that means NMOS CPUs read from the wrong address.

The "fixed version" is left in place, and is the basis for the CMOS variant's JMP indirect. It is correct except for one thing, and that's cycle accuracy.

closes #86

### CODE REVIEW

File: src/instruction.rs [hunk 1]
```diff
@@ -466,3 +468,16 @@ impl crate::Variant for RevisionA {
         }
     }
 }
+
+/// Emulates the 65C02, which has a few bugfixes, and another addressing mode
+pub struct Cmos6502;
+
+impl crate::Variant for Cmos6502 {
+    fn decode(opcode: u8) -> Option<(Instruction, AddressingMode)> {
+        // TODO: We obviously need to add the other CMOS isntructions here.
```
Comment (mre) [inline src/instruction.rs:477]: Typo in instructions

File: src/instruction.rs [hunk 2]
```diff
@@ -127,7 +127,8 @@ pub enum AddressingMode {
     Absolute,         // 3    JMP $1000    full 16-bit address
     AbsoluteX,        // 3    STA $1000,X  full 16-bit address plus X register
     AbsoluteY,        // 3    STA $1000,Y  full 16-bit address plus Y register
-    Indirect,         // 3    JMP ($1000)  jump to address stored at address
+    BuggyIndirect,    // 3    JMP ($1000)  jump to address stored at address
```
Comment (mre) [inline src/instruction.rs:130]: Perhaps we should add a note about what this is for here? Just to mention the hardware bug explicitly. We could add a link to the issue as well.

**Review by mre — APPROVED** [review]

**Comment by mre** [comment]
Good job. 👍

**Comment by omarandlorraine** [comment]
The CI is failing because those comments just won't line up! I'd suggest moving them to their own line, like in most other Rust code, so that cargo fmt is happier.

**Comment by omarandlorraine** [comment]
ready to merge if you agree?

File: src/cpu.rs [hunk 3]
```diff
@@ -136,24 +134,52 @@ impl<M: Bus, V: Variant> CPU<M, V> {
...
                     }
                     AddressingMode::Indirect => {
                         // Use [u8, ..2] from instruction as an address. Interpret the
                         // two bytes starting at that address as an address.
                         // (Output: a 16-bit address)
-                        let slice = read_address(memory, arr_to_addr(&slice));
-                        OpInput::UseAddress(arr_to_addr(&slice))
+                        // TODO: If the pointer ends in 0xff, then incrementing it would propagate
+                        // the carry to the high byte of the pointer. This incurs a cost of one
+                        // machine on the real 65C02, which is not implemented here.
```
Comment (mre) [inline src/cpu.rs:159]:
```suggestion
                        // machine instruction on the real 65C02, which is not implemented here.
```

**Comment by mre** [comment]
Merged it. 😃
