### PR TITLE
Fix SBC implementation and improve overflow detection

### LINKED ISSUE #105: Possible carry bug with SBC
Hello, I encountered a program where mos6502 deviates from the behavior I expected from SBC. I was trying to use this [table lookup multiply](https://www.lysator.liu.se/~nisse/misc/6502-mul.html) from a "C64 old timer" and found that it worked in [masswerk's emulator](https://www.masswerk.at/6502/) but not in mos6502. I narrowed it down to this difference in behavior with SBC:

```rust
use mos6502::memory::Bus;
use mos6502::memory::Memory;
use mos6502::instruction::Nmos6502;
use mos6502::cpu;
use mos6502::registers::Status;
use mos6502::registers::StatusArgs;

fn main() {
    let mut cpu = cpu::CPU::new(Memory::new(), Nmos6502);

    // sbc #0
    cpu.memory.set_byte(0, 0xe9);
    cpu.registers.status = Status::new(
        StatusArgs {
            negative: false,
            overflow: false,
            unused: false,
            brk: false,
            decimal_mode: false,
            disable_interrupts: false,
            zero: true,
            carry: true,
        });

    println!("registers: {:?}", cpu.registers);
    cpu.single_step();
    println!("registers: {:?}", cpu.registers);

    // expected carry to be 1 here, instead is 0
}
```

I'm new to 6502 so correct me if this is one of those things that vary depending on 6502 chip bugs, but it looks to me that, since C=1, and all the registers are 0, `A - M - C̅` should result in 0 without any carrying, so afterwards C=1. This is what happens in masswerk's emulator at least.

### PR DESCRIPTION
**Pull request by mre**
- Correct decimal mode subtraction in SBC operation
- Implement accurate overflow detection for non-decimal mode
- Fix carry flag calculation as inverse of borrow
- Add comments explaining complex bit manipulation for overflow detection
- Update tests to verify correct behavior in both decimal and non-decimal modes

This commit addresses issues with the Subtract with Carry (SBC) operation,
ensuring correct behavior in both decimal and non-decimal modes, and
improves code readability with added comments.

Fixes #105

### CODE REVIEW

**Comment by omarandlorraine** [comment]
Do you know why the corresponding fix is not necessary in the implementation of ADC? The bug is not present there for some reason?

Does this PR supercede #96 ?

(I also happen to know that for reasons having to do with false positives, the ADC and SBC are underrepresented by solid65, maybe that's how the bug crept in to this crate)

File: src/cpu.rs [hunk 1]
```diff
@@ -992,52 +992,97 @@ impl<M: Bus, V: Variant> CPU<M, V> {
...
-            (a_before > 127) && (0u8.wrapping_sub(value).wrapping_sub(nc) > 127) && a_after < 128;
-
-        let did_overflow = over || under;
+        // Calculate a temporary result using wrapping subtraction to handle potential underflow.
+        let temp_result = accumulator_before
+            .wrapping_sub(value)
+            .wrapping_sub(1 - carry);
 
-        let mask = Status::PS_CARRY | Status::PS_OVERFLOW;
+        // Branch on whether we're in decimal mode
```
Comment (omarandlorraine) [inline src/cpu.rs:1010]: this is a way better approach

**Comment by omarandlorraine** [comment]
I'm happy with this, good job

**Comment by mre** [comment]
> Do you know why the corresponding fix is not necessary in the implementation of ADC? The bug is not present there for some reason?
> 
> Does this PR supercede #96 ?
> 
> (I also happen to know that for reasons having to do with false positives, the ADC and SBC are underrepresented by solid65, maybe that's how the bug crept in to this crate)

Oh, I just made the minimal change for now to see if I correctly understood the issue. The ADC is probably broken, too. We can tackle that next. 

I think we can rebase #96 on top of `master` to see where we're at once this is merged.

**Comment by mre** [comment]
Merged. Thanks for the quick review.
